# Generated by Django 5.2.7 on 2025-10-28 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='세션 ID', max_length=100, null=True)),
                ('total_requests', models.IntegerField(default=0, help_text='총 요청 수')),
                ('successful_requests', models.IntegerField(default=0, help_text='성공한 요청 수')),
                ('failed_requests', models.IntegerField(default=0, help_text='실패한 요청 수')),
                ('average_response_time', models.FloatField(default=0, help_text='평균 응답 시간')),
                ('average_confidence', models.FloatField(default=0, help_text='평균 신뢰도')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='메트릭 생성 시간')),
            ],
            options={
                'db_table': 'chat_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='대화 세션 ID', max_length=100, unique=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='사용자 IP', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='대화 시작 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 대화 시간')),
                ('is_active', models.BooleanField(default=True, help_text='활성 대화 여부')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], help_text='로그 레벨', max_length=10)),
                ('message', models.TextField(help_text='로그 메시지')),
                ('module', models.CharField(blank=True, help_text='모듈명', max_length=100, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='사용자 IP', null=True)),
                ('session_id', models.CharField(blank=True, help_text='세션 ID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='로그 생성 시간')),
            ],
            options={
                'db_table': 'chat_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='chat_logs_level_a72a80_idx'), models.Index(fields=['session_id', 'created_at'], name='chat_logs_session_a35c0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '사용자 질문'), ('bot', '챗봇 답변'), ('system', '시스템 메시지')], help_text='메시지 타입', max_length=10)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('confidence', models.FloatField(blank=True, help_text='답변 신뢰도 (0-1)', null=True)),
                ('sources', models.JSONField(blank=True, help_text='참조 소스 정보', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='처리 시간 (초)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='메시지 생성 시간')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_proxy.conversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
